# Generated by Django 4.2.6 on 2023-12-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='vote_type',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
