# Generated by Django 4.2.6 on 2023-12-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_answer_delete_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
