# Generated by Django 4.2.6 on 2024-04-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
