# Generated by Django 4.2.6 on 2024-04-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_alter_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
