# Generated by Django 4.2.6 on 2023-12-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='github_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkdin_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
