# Generated by Django 4.2.6 on 2024-04-09 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='uid',
        ),
    ]
