# Generated by Django 4.2.6 on 2024-05-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.CharField(error_messages={'blank': 'این فیلد نمی\u200cتواند خالی باشد.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'این ایمیل قبلاً ثبت شده است.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='github_link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkdin_link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, error_messages={'invalid_image': 'تصویر معتبر نیست.'}, null=True, upload_to='users/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'این نام کاربری قبلاً استفاده شده است.'}, max_length=150, unique=True),
        ),
    ]
