# Generated by Django 4.2.6 on 2024-05-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_bio_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='github_link',
            field=models.URLField(blank=True, error_messages={'invalid': 'لینک Github معتبر نیست.'}, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkdin_link',
            field=models.URLField(blank=True, error_messages={'invalid': 'لینک LinkedIn معتبر نیست.'}, max_length=250, null=True),
        ),
    ]
