# Generated by Django 4.2.6 on 2024-05-21 09:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_github_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='github_link',
            field=models.URLField(blank=True, max_length=250, null=True, validators=[accounts.models.CustomURLValidator]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkdin_link',
            field=models.URLField(blank=True, max_length=250, null=True, validators=[accounts.models.CustomURLValidator]),
        ),
    ]
