# Generated by Django 4.2.6 on 2024-05-31 12:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, error_messages={'invalid_image': 'تصویر معتبر نیست.'}, null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
