# Generated by Django 4.2.6 on 2024-06-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_bio_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'این ایمیل قبلاً ثبت شده است.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'این نام کاربری قبلاً استفاده شده است.'}, max_length=150, unique=True),
        ),
    ]
