# Generated by Django 4.2.6 on 2024-04-10 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_department_tag_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.department'),
        ),
    ]
