# Generated by Django 4.2.6 on 2024-04-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_alter_tag_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='department',
        ),
        migrations.AddField(
            model_name='tag',
            name='department',
            field=models.ManyToManyField(to='tags.department'),
        ),
    ]
