# Generated by Django 4.2.6 on 2024-04-11 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_remove_tag_department_tag_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='department',
        ),
        migrations.AddField(
            model_name='tag',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tags.department'),
            preserve_default=False,
        ),
    ]
